brew_packages:
  - ansible
  - autoenv
  - asciinema
  - cask
  - cfssl
  - curl
  - docker-compose
  - etcd
  - freetype
  - flake8
  - git
  - gnu-tar
  - gnupg
  - gnutls
  - gource
  - htop
  - ifstat
  - imagemagick
  - ipython
  - jq
  - kubernetes-cli
  - mypy
  - mysql
  - neofetch
  - node
  - openssl
  - pipenv
  - postgresql
  - python@2
  - python
  - shellcheck
  - sphinx-doc
  - sqlite
  - tcptraceroute
  - watch
  - wget
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-syntax-highlighting
