- name: Create vim colors directory
  file:
    path: ~/.vim/colors
    state: directory
- name: Downloading VIM color scheme
  shell: curl -LSso ~/.vim/colors/monokai.vim https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
